env:
  global:
  - secure: e3qyrQ2dZ5FdcBsfkOZa3stF4XDlg72U14RqCrbTrZc96lEOTUO70g+fUdmTBtj7oGwm+nH7nybQfychs+juTl3YKE/RuV0SiWyX6XdDpDOZILG+SI8VgAly7ZW+zoNLG0Q2cDgfeUC5qdhMaGGSEPq9BR83FguIMMoQOYbL6t+JhTb6282LdnpFR+j081qh1AMzbFkUE/NhmYqaazl42Bax/eNreMa/yIeITSXAny757OLMpCmQ2v4ZjqVP2Shq8JxAEg8cqJ541e3RHJFt+56N+I7rshLZ+ls+JUgcVau/BPS2cnAcgY4r0CIAVK2YdWzG2oz9pbo1uw1rdLwNQ3Eh8gfCdtdjHHhrwrd86VvnHcv9F+rVa/AqEnSZjYw4+mzW6u7PHjCVlM4LkAHCQY5+7WDJifz99G7kPhdU4zEBoX2dbf3K58/thjbIhX5Mz1xcoRfAHb0G7cI67QY45BOMtJJyHf/1MZdqbK7nMAU/XB1/JQ3ZqclX3DZObEbFH6TmCjKn4LiBJaX4tZRA1unFWdLYWVREjIqpjSQ5zhAI+6OFBHHtmNRKyeIe8VqYJCwxT8MkHJmF0bLPqK+7HkXxvMVjllBlXK+VLJUdA26Y4yXSLfNM2SQvsWcR2KuLnpZ450deq38H3V4c1l3Z+ND13L/rfG15G/j9C5akJGY=
  - secure: K21dE8l9eSHA9t0FDJYlE4RA8QDKZgKuRr+Of3/EbkiOSnC60jyXCRexwHAJWc/mWnbPbXMjIjHHDgeGpblPp/TUOk7HokflF4StrwSeBqAeGYX+WiyAUQ8ZwM+0fapOVl3v5mxnccj+qX7eX17OgSI85Mb7wkQOST1Q/phbRw+ELyBwF8US3R51jx6kCj15ElsJ9+4gElmj0el/I/ZdTc17WFHdYSwBEI6o89UJhdwtpkA9c44SZJZpL+lQHJCii2dnmG89yQwBnhxIVDlA8nVK8vJHKWshY7MqYWcNebbvWeFseeOBgrKjOpUiDZrqVMmFiI3kCt76saBG284wYaaRuX6lOThuIGoQ/vmI8PzJgxJPcVBOxULFsQanFtheU5JHLK4zu4NKXvvqXpkFJIXVUtCAVaQNKgmXSQFD5TF4xl4/GKwToFJCPCi0al3fzTWOK07XQRfKJ96V2qZpJ6R8rSxCLa6OZAEnlNEqEN9ns2IuF3MoXQKHzL6V4XX2KKXjC85j1fP9ZF4u1rUY8t95hIN9r6KenhF9Fwy8NUoq1zfDh5JwieI5VE14+ed/kpiZ9M7vBfAJRP/yaWhypmGr/9oe6P8hy/UnhuVD2ztQmEyk0xu5lJfMdI4nOMGpIlVedsIrZ8D8FqiSEuV6hop2CqGwiuruE/JKiFQnKR4=

services:
- docker

addons:
  sonarcloud:
    organization: departement-loire-atlantique
    token:
      secure: gnN3mAzYmE70aaq0JXO+pvdHPF03/8dcOw27DSw8lOousmlqbR2a/El0bl6ewgZo4Ob8fFuLrVRdr6nrROe5yqpwABayKfbiyDmhxRisvzymr0aWhdIkIIYxOXg26S3s4k00ATXwirtMGyHGbmIMc33jx19TjTA7XvPtPVHEG1EDct+Qhro7884snwvwy5/gR24G8xhNumlkKIKwfraclPRQNx96oXWsWozeWMrPtSxQC6vvbabMZaN+TiZY/gA51Ml40w7pRVu75JHA22hsANRQnlnVy4hKaazyBPQn8aJ9Q1gzRKjyB/fZA/4CHC2cDFfCBQTY6m0EgK7/pinvorUOeNAK9VVGNQevL0nS8kew51HVUdwjfhftOHLQCoNNyxk2BgOqnWqEDY+jvsDGSH8/CxpNpTCYUdwkn392Sldz6vxe2F22wLIzAGqJiQEVpCTbGTzZwXSqGCb0AwWVWaBFFmm6vGArz7s6c4TWfxyhnweRdnLp6Tt15Gt/+yBj7QMT1TWZjmlOtCauKUdYJFpotlqX1nq1hNjtZYsFn/dMZlWcWfG3jLUmvppwGpg54cwyxWRnK/RGb6kl83djUKUDvGlQ8W+ekGqNMsMV1jIbKSTSkaZIAt+8bHZnvqJ5CXoQII60xRYiAYqIpal0GJb/HH3Ck6NNvZDysts4/+o=

before_script:
- echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
- docker pull sguellec/jplatformbuild

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/source --name buildimage -t sguellec/jplatformbuild
- docker cp buildimage:/root/dist .
- export CODE_VERSION=`git describe`
- sonar-scanner -Dsonar.projectVersion=$CODE_VERSION

deploy:
  provider: releases
  api_key:
    secure: ByT6zMWetpaFT2vuGCuchPf++rUEPmR4TIG34wUCkwMRJAmW2uoy5ckKkXNjgra4aaPUjtM6ISQnG8GeOshwBQQgehzdSIThAi0J7DltemArKa+Kz1EOZGpMC497KUgTYbmmpgqXjSFWg4D+09pfPA7kH4iCiT9ysoUeqvLAOHdZwE5EGb4EiEh8IxZsXuWevVFiOiHm2PMA1psXRRdfzl1NG5DJfRf7fCLVzyboTuN7afzWLjRDGCew/Ypv9Yyff591GxPL/lv2aP7KpdYa3c6utWxEDrTBLF5IdCCVEWYNH5iV83Tl+CPOYmL6StHj2DLtoFhwpOh6udTuTPu285KXHpuUN/gpMnqyR62bcNsgrMQcg2tTJuUE8WbsLIyvn5aDPiBW7IFB4AVBQ1mSkG79AQT+FEDxzCiaeQpv7P6qnZ0x9djTkKJCxsv/stP+fdnrqdkDIGzIXY0C1H6ND1CpxQAhquwdyhhHWLvS7Dw7J26Jd55WkLF6feWJG03HzRiv2DwsyU/zoRZQN+2E7x0TYfgOB0u/hAuLJ1Agr0o2Vnqjfl15Xq2WpBg0ZoeggsArTEjwdHUFl28ZRK0rmYX9Z7++0s3LfVR0I+lX2EWwI1obZeVq2iyuCwBHq3g221QszyUXEWSnzif2+fIU/wXm+1je0IaVfETlOSTTQWc=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
