env:
  global:
  - secure: e3qyrQ2dZ5FdcBsfkOZa3stF4XDlg72U14RqCrbTrZc96lEOTUO70g+fUdmTBtj7oGwm+nH7nybQfychs+juTl3YKE/RuV0SiWyX6XdDpDOZILG+SI8VgAly7ZW+zoNLG0Q2cDgfeUC5qdhMaGGSEPq9BR83FguIMMoQOYbL6t+JhTb6282LdnpFR+j081qh1AMzbFkUE/NhmYqaazl42Bax/eNreMa/yIeITSXAny757OLMpCmQ2v4ZjqVP2Shq8JxAEg8cqJ541e3RHJFt+56N+I7rshLZ+ls+JUgcVau/BPS2cnAcgY4r0CIAVK2YdWzG2oz9pbo1uw1rdLwNQ3Eh8gfCdtdjHHhrwrd86VvnHcv9F+rVa/AqEnSZjYw4+mzW6u7PHjCVlM4LkAHCQY5+7WDJifz99G7kPhdU4zEBoX2dbf3K58/thjbIhX5Mz1xcoRfAHb0G7cI67QY45BOMtJJyHf/1MZdqbK7nMAU/XB1/JQ3ZqclX3DZObEbFH6TmCjKn4LiBJaX4tZRA1unFWdLYWVREjIqpjSQ5zhAI+6OFBHHtmNRKyeIe8VqYJCwxT8MkHJmF0bLPqK+7HkXxvMVjllBlXK+VLJUdA26Y4yXSLfNM2SQvsWcR2KuLnpZ450deq38H3V4c1l3Z+ND13L/rfG15G/j9C5akJGY=
  - secure: K21dE8l9eSHA9t0FDJYlE4RA8QDKZgKuRr+Of3/EbkiOSnC60jyXCRexwHAJWc/mWnbPbXMjIjHHDgeGpblPp/TUOk7HokflF4StrwSeBqAeGYX+WiyAUQ8ZwM+0fapOVl3v5mxnccj+qX7eX17OgSI85Mb7wkQOST1Q/phbRw+ELyBwF8US3R51jx6kCj15ElsJ9+4gElmj0el/I/ZdTc17WFHdYSwBEI6o89UJhdwtpkA9c44SZJZpL+lQHJCii2dnmG89yQwBnhxIVDlA8nVK8vJHKWshY7MqYWcNebbvWeFseeOBgrKjOpUiDZrqVMmFiI3kCt76saBG284wYaaRuX6lOThuIGoQ/vmI8PzJgxJPcVBOxULFsQanFtheU5JHLK4zu4NKXvvqXpkFJIXVUtCAVaQNKgmXSQFD5TF4xl4/GKwToFJCPCi0al3fzTWOK07XQRfKJ96V2qZpJ6R8rSxCLa6OZAEnlNEqEN9ns2IuF3MoXQKHzL6V4XX2KKXjC85j1fP9ZF4u1rUY8t95hIN9r6KenhF9Fwy8NUoq1zfDh5JwieI5VE14+ed/kpiZ9M7vBfAJRP/yaWhypmGr/9oe6P8hy/UnhuVD2ztQmEyk0xu5lJfMdI4nOMGpIlVedsIrZ8D8FqiSEuV6hop2CqGwiuruE/JKiFQnKR4=

services:
- docker

addons:
  sonarcloud:
    organization: departement-loire-atlantiqu-1
    token:
      secure: Udq+ykA5sG8Gah/rNX63ybHHMCA+65Bg6Hhq7oBxaTE4C15RsWSBRNgyhmp9YS75FRKp1WdjLuLSg6WUMqPVp66sOQWScN6jdm4lz+VZ0eDEQiqwpTvfAU3kkRgYB4/9qBPx5YaeRduAo21yx7RE4taH9wM5zuEa6YJnQM24BPbs/kSfLqQ5jhaGjuXJvu8stmUNQlcPRYF6u7qbHS1v+k3tMwLwIuIG6GqlpcKUaK42PgHdV0IEl2NN43i0VKXtasFFGo7x5NbZI6wGQ9YGuIoiW4sRfwU0rNWBP4gvG8LU/fVu3nw87mc01pfu5KkiN21kWqYAAdBGTSwsr7J8CGtd16u6VWBFJ/lAwRmwafZzdRB1StHJBAEAxOzwb6TU3/AQKIaRVjm5UlUyaO2q/sVQeImpkFU3BCKLyGsnZlgMR2xJIMkKui6CtM8oUz/N6uotpBVwOl9hA+FKXblvkMz2nes3tSiWlO0UbTX8c2saE8rSjhBPwfqIVAf9UitIcOG4nI5epnTJlPJ77U7E1LoEHKdKhNr2Vm6yT+O1c4BEKwso/359+9GArry0rhQSD/411tOOwXG70Iu2jaxgBCCumqUgnsdfav5RUOqsqXOvpZqzP79eDRIIMhTc2DLKxDtbOcbxykZKGOSD4rVapVYsZgeME0S3vpwA2z8g42M=

before_script:
- echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
- docker pull sguellec/jplatformbuild

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/source --name buildimage -t sguellec/jplatformbuild
- docker cp buildimage:/root/dist .
- export CODE_VERSION=`git describe`
- sonar-scanner -Dsonar.projectVersion=$CODE_VERSION

deploy:
  provider: releases
  api_key:
    secure: ByT6zMWetpaFT2vuGCuchPf++rUEPmR4TIG34wUCkwMRJAmW2uoy5ckKkXNjgra4aaPUjtM6ISQnG8GeOshwBQQgehzdSIThAi0J7DltemArKa+Kz1EOZGpMC497KUgTYbmmpgqXjSFWg4D+09pfPA7kH4iCiT9ysoUeqvLAOHdZwE5EGb4EiEh8IxZsXuWevVFiOiHm2PMA1psXRRdfzl1NG5DJfRf7fCLVzyboTuN7afzWLjRDGCew/Ypv9Yyff591GxPL/lv2aP7KpdYa3c6utWxEDrTBLF5IdCCVEWYNH5iV83Tl+CPOYmL6StHj2DLtoFhwpOh6udTuTPu285KXHpuUN/gpMnqyR62bcNsgrMQcg2tTJuUE8WbsLIyvn5aDPiBW7IFB4AVBQ1mSkG79AQT+FEDxzCiaeQpv7P6qnZ0x9djTkKJCxsv/stP+fdnrqdkDIGzIXY0C1H6ND1CpxQAhquwdyhhHWLvS7Dw7J26Jd55WkLF6feWJG03HzRiv2DwsyU/zoRZQN+2E7x0TYfgOB0u/hAuLJ1Agr0o2Vnqjfl15Xq2WpBg0ZoeggsArTEjwdHUFl28ZRK0rmYX9Z7++0s3LfVR0I+lX2EWwI1obZeVq2iyuCwBHq3g221QszyUXEWSnzif2+fIU/wXm+1je0IaVfETlOSTTQWc=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
